Update push-to-harbor.yml
test1

diff --git a/.github/workflows/push-to-harbor.yml b/.github/workflows/push-to-harbor.yml
--- a/.github/workflows/push-to-harbor.yml
+++ b/.github/workflows/push-to-harbor.yml
@@ -13,7 +13,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Log in to Harbor
-        run: echo "Hello World"
+        run: curl --fail -v http://localhost:5000/run-playwright || echo "Failed to trigger Playwright"
 
       - name: Build Docker Image
         run: docker pull nginx
